app:
  environment:
    name: "Production Server"
  message: "Hello from Production Environment!"
  database:
    max-connections: 50
    connection-timeout: 5000
  security:
    jwt-expiration-seconds: 3600
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
logging:
  level:
    root: WARN
    com.example: INFO